# Metody analizy danych. Lab 4. Wprowadzenie do biblioteki pandas

## 1. Struktury danych w bibliotece pandas

Podstawową strukturą danych w bibliotece pandas jest ramka danych, obiekt typu `DataFrame` oraz seria danych, `Series`, która stanowi pojedynczą kolumnę ramki danych. Pod tymi strukturami kryją się tablice numpy, które poznaliśmy już na zajęciach wcześniejszych. Każda kolumna w ramce danych jest określona typem danych, który jest w niej przechowywany, z uwzględnieniem sytuacji, w której możliwe jest również przechowywanie wartości brakujących (typ `Nan` - not a number).

### 1.1 Inicjalizacja ramek oraz serii danych

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import numpy as np

Seria danych w pandas to struktura, która oprócz danych w postaci wektora zawiera również indeks, który może być dowolnego typu, pod warunkiem, że jest typem hashowalnym w Pythonie. Poniżej kilka przykładów inicjalizacji serii danych.

In [4]:
# wyświetlenie docstringa dla klasy pandas.Series
print(pd.Series.__doc__)

    One-dimensional ndarray with axis labels (including time series).

    Labels need not be unique but must be a hashable type. The object
    supports both integer- and label-based indexing and provides a host of
    methods for performing operations involving the index. Statistical
    methods from ndarray have been overridden to automatically exclude
    missing data (currently represented as NaN).

    Operations between Series (+, -, /, \*, \*\*) align values based on their
    associated index values-- they need not be the same length. The result
    index will be the sorted union of the two indexes.

    Parameters
    ----------
    data : array-like, Iterable, dict, or scalar value
        Contains data stored in Series. If data is a dict, argument order is
        maintained.
    index : array-like or Index (1d)
        Values must be hashable and have the same length as `data`.
        Non-unique index values are allowed. Will default to
        RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
        and index is None, then the keys in the data are used as the index. If the
        index is not None, the resulting Series is reindexed with the index values.
    dtype : str, numpy.dtype, or ExtensionDtype, optional
        Data type for the output Series. If not specified, this will be
        inferred from `data`.
        See the :ref:`user guide <basics.dtypes>` for more usages.
    name : Hashable, default None
        The name to give to the Series.
    copy : bool, default False
        Copy input data. Only affects Series or 1d ndarray input. See examples.

    Notes
    -----
    Please reference the :ref:`User Guide <basics.series>` for more information.

    Examples
    --------
    Constructing Series from a dictionary with an Index specified

    >>> d = {'a': 1, 'b': 2, 'c': 3}
    >>> ser = pd.Series(data=d, index=['a', 'b', 'c'])
    >>> ser
    a   1
    b   2
    c   3
    dtype: int64

    The keys of the dictionary match with the Index values, hence the Index
    values have no effect.

    >>> d = {'a': 1, 'b': 2, 'c': 3}
    >>> ser = pd.Series(data=d, index=['x', 'y', 'z'])
    >>> ser
    x   NaN
    y   NaN
    z   NaN
    dtype: float64

    Note that the Index is first build with the keys from the dictionary.
    After this the Series is reindexed with the given Index values, hence we
    get all NaN as a result.

    Constructing Series from a list with `copy=False`.

    >>> r = [1, 2]
    >>> ser = pd.Series(r, copy=False)
    >>> ser.iloc[0] = 999
    >>> r
    [1, 2]
    >>> ser
    0    999
    1      2
    dtype: int64

    Due to input data type the Series has a `copy` of
    the original data even though `copy=False`, so
    the data is unchanged.

    Constructing Series from a 1d ndarray with `copy=False`.

    >>> r = np.array([1, 2])
    >>> ser = pd.Series(r, copy=False)
    >>> ser.iloc[0] = 999
    >>> r
    array([999,   2])
    >>> ser
    0    999
    1      2
    dtype: int64

    Due to input data type the Series has a `view` on
    the original data, so
    the data is changed as well.

**Przykład 1**

In [ ]:
# możemy zainicjalizowac pustą serię
series_1 = pd.Series()
series_1

Series([], dtype: object)

In [ ]:
# główne statystyki opisowe, dostępne również dla ramki danych
series_1.describe()

count       0
unique      0
top       NaN
freq      NaN
dtype: object

**Przykład 2**

In [ ]:
dane = list(range(1,6))
series_2 = pd.Series(dane)
series_2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# teraz widać więcej
series_2.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

**Przykład 3**

In [ ]:
# seria ze słownika
data = {key: val for key,val in zip('abcd',[1,2,3,4])}
print(f"Słownik: {data}")
series_3 = pd.Series(data)
series_3

Słownik: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
series_3.index

Index(['a', 'b', 'c', 'd'], dtype='object')

**Przykład 4**

In [ ]:
# możliwa jest ponowna konwersja do listy
# metody tolist() oraz to_list()
series_3.tolist()

[1, 2, 3, 4]

In [ ]:
series_3.index.tolist()

['a', 'b', 'c', 'd']

**Przykład 5**

In [ ]:
# patrząc na docstring dla Series widzimy, że operacje arytmetyczne na seriach danych również są możliwe
# pod warunkiem zachowania odpowiednich reguł (długość wektora danych serii)
series_3 + series_3

a    2
b    4
c    6
d    8
dtype: int64

In [ ]:
series_3 ** 2

a     1
b     4
c     9
d    16
dtype: int64

In [ ]:
series_3

a    1
b    2
c    3
d    4
dtype: int64

**Przykład 6**

In [ ]:
# możemy również wykorzystać pewne własności biblioteki numpy związane ze zwracaniem kopii i widoków tablic
# poniżej przykład pokazujący jak stworzyć serię danych, która jest widokiem na tablicę numpy
arr = np.arange(1, 6)
print(arr)
series_4 = pd.Series(arr, copy=False)
series_4

[1 2 3 4 5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# własność values zwraca dane serii jako tablica numpy
# porównujemy bazę obu tablic - jeżeli ta sama, to wskazują one na ten sam obszar pamięci
series_4.values.base == arr.base

True

In [ ]:
# to powoduje, że możemy współdzielić tę pamięć ze wszystkimi dogodnościami
# i konsekwencjami również (mniejsza ilość zaalokowanej pamięci ale brak rozdzielenia danych w
# przypadku modyfikacji poprzez którykolwiek z widoków)

# modyfikacja powoduje oczywiście zmianę wartości dla każdego widoku na tę zmienną
arr[0] = 99
print(arr)
print(series_4)

[99  2  3  4  5]
0    99
1     2
2     3
3     4
4     5
dtype: int64

**Przykład 7**

In [ ]:
# serii można nadać nazwę, chociaż nie jest to szczególnie przydatne
series_4.name = "wiek"
series_4

0    99
1     2
2     3
3     4
4     5
Name: wiek, dtype: int64

**Przykład 8**

In [ ]:
# generujemy szereg czasowy dzięki funkcji date_range(początek, ilość okresów, interwał)
timeseries = pd.date_range('2025-03-20 12:00:00', periods=6, freq='h')
timeseries

DatetimeIndex(['2025-03-20 12:00:00', '2025-03-20 13:00:00',
               '2025-03-20 14:00:00', '2025-03-20 15:00:00',
               '2025-03-20 16:00:00', '2025-03-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [ ]:
# pandas series posiada również specjalny typ indeksu dla danych typu szereg czasowy
# tutaj sfabrykujemy takie dane, ale mogą one być wczytane z plików
data = [f'event {n}' for n in range(1, 7)]
timeseries = pd.Series(data, index=timeseries)
timeseries

2025-03-20 12:00:00    event 1
2025-03-20 13:00:00    event 2
2025-03-20 14:00:00    event 3
2025-03-20 15:00:00    event 4
2025-03-20 16:00:00    event 5
2025-03-20 17:00:00    event 6
Freq: h, dtype: object

In [ ]:
timeseries.index

DatetimeIndex(['2025-03-20 12:00:00', '2025-03-20 13:00:00',
               '2025-03-20 14:00:00', '2025-03-20 15:00:00',
               '2025-03-20 16:00:00', '2025-03-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

**Inicjalizacja ramek danych pandas**

Podobnie jak w przypadku serii danych mamy możliwość konwersji innych struktur danych na ramkę danych, z zachowaniem pewnych warunków. Zacznijmy od listy.

**Przykład 9**

In [ ]:
df_1 = pd.DataFrame([f'rekord {n}' for n in range(1, 6)])
df_1

          0
0  rekord 1
1  rekord 2
2  rekord 3
3  rekord 4
4  rekord 5

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

In [ ]:
df_1.describe()

               0
count          5
unique         5
top     rekord 1
freq           1

In [ ]:
print(df_1.ndim, df_1.dtypes, df_1.shape, sep='\n')

2
0    object
dtype: object
(5, 1)

In [ ]:
df_1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# kolekcja kolumn
df_1.columns

RangeIndex(start=0, stop=1, step=1)

In [ ]:
df_1.columns = ['kolumna 1']
df_1

  kolumna 1
0  rekord 1
1  rekord 2
2  rekord 3
3  rekord 4
4  rekord 5

**Przykład 10**

In [ ]:
# dostęp do danych wewnątrz serii i ramek możliwy jest na wiele sposobów
# tu odwołujemy się do pojedynczej kolumny, co jak widać jest domyślną osią wyszukiwania tej wartości (etykiety kolumny)
df_1['kolumna 1']

0    rekord 1
1    rekord 2
2    rekord 3
3    rekord 4
4    rekord 5
Name: kolumna 1, dtype: object

In [ ]:
# ta pojedyncza kolumna to jest seria danych
type(df_1['kolumna 1'])

pandas.core.series.Series

**Przykład 11**

In [ ]:
# istnieje przeciążony konstruktor DataFrame, który między innymi pozwala na konwersję zagnieżdżonej listy
# (tu dwupoziomowej) do ramki danych bez żadnych dodatkowych przekształceń
nested_list = [[1,2,3,4] for _ in range(4)]
df_2 = pd.DataFrame(nested_list, columns=list('ABCD'))
df_2

   A  B  C  D
0  1  2  3  4
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4

In [ ]:
# describe działa dla wszystkich kolumn o typie numerycznym
df_2.describe()

         A    B    C    D
count  4.0  4.0  4.0  4.0
mean   1.0  2.0  3.0  4.0
std    0.0  0.0  0.0  0.0
min    1.0  2.0  3.0  4.0
25%    1.0  2.0  3.0  4.0
50%    1.0  2.0  3.0  4.0
75%    1.0  2.0  3.0  4.0
max    1.0  2.0  3.0  4.0

**Przykład 12**

In [ ]:
df_2['D'] = df_2['D'].astype(str)
df_2.describe()

         A    B    C
count  4.0  4.0  4.0
mean   1.0  2.0  3.0
std    0.0  0.0  0.0
min    1.0  2.0  3.0
25%    1.0  2.0  3.0
50%    1.0  2.0  3.0
75%    1.0  2.0  3.0
max    1.0  2.0  3.0

**Przykład 13**

In [ ]:
# inicjalizacja ramki ze słownika - tu minimalny przykład aby zobrazować potrzebną postać słownika
# klucze słownika
data_dict = {'label': 'computer', 'price': 1999.0}
df_3 = pd.DataFrame(data_dict, index=list(range(1)))
df_3

      label   price
0  computer  1999.0

**Przykład 14**

In [ ]:
# to zapewne nie jest efekt, którego oczekiwaliśmy
df_4 = pd.DataFrame(data_dict, index=list(range(len(data_dict))))
df_4

      label   price
0  computer  1999.0
1  computer  1999.0

**Przykład 15**

In [ ]:
# teraz lepiej - klucz: lista wartości
data_dict = {'label': ['computer', 'monitor', 'mouse'], 'price': [1999.0, 299.0, 30]}
df_5 = pd.DataFrame(data_dict)
df_5

      label   price
0  computer  1999.0
1   monitor   299.0
2     mouse    30.0

**Wczytywanie danych do ramki z plików**

Listę dostępnych funkcji odczytu i zapisu danych z i do ramek pandas można znaleźć w dokumentacji pod adresem: https://pandas.pydata.org/docs/reference/io.html

Poniżej zostaną zaprezentowane przykłady z wybranymi opcjami.

In [ ]:
# wczytanie danych do ramki z pliku
# wyświetlamy pierwsze 5 linii z pliku (może nie zadziałać w zależności od konfiguracji systemu operacyjnego)
! head -5 iris.data

sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa

**Przykład 16**

In [ ]:
# wczytujemy dane do pliku wykorzystując funkcję read_csv, z domyślnymi parametrami (separator, kodowanie, obsługa błędów, nagłówek i inne)
df_6 = pd.read_csv('iris.data')
df_6

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sepal length in cm  150 non-null    float64
 1   sepal width in cm   150 non-null    float64
 2   petal length in cm  150 non-null    float64
 3   petal width in cm   150 non-null    float64
 4   class               150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

**Przykład 17**

In [ ]:
df_7 = pd.read_table('iris.data', sep=',')
df_7

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

**Przykład 18**

In [ ]:
# jeżeli plik nie posiada wiersza nagłówkowego to możemy taką opcję wskazać czy jego wczytywaniu
# najpierw jednak zapiszmy dane do pliku csv wykorzystując funkcję to_csv

# ścieżka do pliku, separator, czy zapisać nagłówek, czy zapisać index (jeżeli został utworzony
# w trakcie ładowania danych do ramki to zazwyczaj nie chcemy go zapisywać), kodowanie znaków
df_7.to_csv('iris.csv', sep=';', header=True, index=False, encoding='utf-8')

In [ ]:
! head -5 iris.csv

sepal length in cm;sepal width in cm;petal length in cm;petal width in cm;class
5.1;3.5;1.4;0.2;Iris-setosa
4.9;3.0;1.4;0.2;Iris-setosa
4.7;3.2;1.3;0.2;Iris-setosa
4.6;3.1;1.5;0.2;Iris-setosa

### Zadania

**Zadanie 1**

Stwórz serię danych, której dane to wartości całkowite od 1 do 100, a indeks jest postaci od ean_001 do ean_100.

**Zadanie 2**

Stwórz tablicę numpy o dwóch wymiarach w rozmiarze 10x10, której wartości są zapisane wg. poniższego schematu:
```python
[
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024],
    [3, 9, 27 ... ],
    ...
    [10, 100, 1000, ... ]
]
```
W pierwszej kolumnie znajduje się liczba, która następnie jest w kolejnych kolumnach podnoszona do kwadratu. Zdefiniuj tę tablicę wedle swojego uznania, ale nie jest dopuszczalne wpisanie tych danych "ręcznie".

Stwórz z tych danych ramkę pandas. Kolumny nazwij wg. schematu ['base', 'pow_2', 'pow_3', ..., 'pow_10']

**Zadanie 3**

Sprawdź czy tablica numpy z zadania poprzedniego oraz ramka pandas współdzielą ze sobą dane. Jeżeli nie to stwórz kolejną ramkę, która będzie te dane z tablicą współdzieliła (możesz wykorzystać sposób sprawdzenia tego z labów poprzednich).

**Zadanie 4**

Sprawdź jaki jest przydzielony typ danych w ramce z zadania poprzedniego. Czy można go downcastować do typu, który zapewni zachowanie oryginalnych danych, ale zmniejszy ilość niezbędnej pamięci do ich przechowania? Odpowiedź uzasadnij odnpowienim przykładem w kodzie.

**Zadanie 5**

Wczytaj dane z pliku `iris.data` za pomocą funkcji `read_csv` do zmiennej `iris` jak w przykładzie.

**Zadanie 6**

Zamień nazwy kolumn w ramce `iris` tak, aby w miejsce spacji wstawić znak `_`. Wyświetl pierwsze 10 wierszy tej ramki.

**Zadanie 7**

Sprawdź metodą `memory_usage()` (z parametrem deep=True oraz bez niego) ile danych zajmuje ramka. Wybierz jeden z typów danych numerycznych rodzaju float o mniejszej precyzji i zapisz ramkę w nowej zmiennej `iris_smaller`, której kolumny numeryczne będą rzutowane na ten nowy typ float. Ponownie sprawdź ile pamięci zostało dla ramki zaalokowane.

**Zadanie 8**

Zapisz ramkę do schowka (funkcja `to_clipboard()`), a następnie wklej schowek do edytora tekstowego oraz dowolnego arkusza kalkulacyjnego. Sprawdź format tych danych.

Teraz skopiuj do schowka część z tych wklejonych danych i zapisz do nowej ramki metodą `from_clipboard()`.
Wyświetl pierwsze 5 wierszy tej ramki.

Rozwiązanie zadania to jedynie wywołanie powyższej funkcji, reszta dla informacji i wiedzy studenta.

**Zadanie 9**

Zapisz ramkę do formatów `parquet`, `json` oraz `pickle` (możliwe, że konieczne będzie doinstalowanie nowych pakietów) korzystając z odpowiednich funkcji opisanych w dokumentacji (link w materiałach).

In [9]:
#zadanie 1
index = []
for i in range (1, 101):
  index.append(f"ean{i:03d}")

series = pd.Series(range(1,101), index = index)
series

ean001      1
ean002      2
ean003      3
ean004      4
ean005      5
         ...
ean096     96
ean097     97
ean098     98
ean099     99
ean100    100
Length: 100, dtype: int64

In [18]:
#zadanie 2
podstawy = np.arange(1,11).reshape(10,1)
wykladniki = np.arange(1,11).reshape(1,10)
tablica = podstawy ** wykladniki

kolumny = []
for i in range (1,11):
  if i == 1:
    kolumny.append("base")
  else:
    kolumny.append(f"pow_{i}")

df = pd.DataFrame(tablica, columns=kolumny)
print(df)

   base  pow_2  pow_3  pow_4   pow_5    pow_6     pow_7      pow_8  \
0     1      1      1      1       1        1         1          1
1     2      4      8     16      32       64       128        256
2     3      9     27     81     243      729      2187       6561
3     4     16     64    256    1024     4096     16384      65536
4     5     25    125    625    3125    15625     78125     390625
5     6     36    216   1296    7776    46656    279936    1679616
6     7     49    343   2401   16807   117649    823543    5764801
7     8     64    512   4096   32768   262144   2097152   16777216
8     9     81    729   6561   59049   531441   4782969   43046721
9    10    100   1000  10000  100000  1000000  10000000  100000000

        pow_9       pow_10
0           1            1
1         512         1024
2       19683        59049
3      262144      1048576
4     1953125      9765625
5    10077696     60466176
6    40353607    282475249
7   134217728   1073741824
8   387420489   3486784401
9  1000000000  10000000000

In [ ]:
#zadanie 3